### ISSUE TITLE
Arguments for process_template

### ISSUE THREAD

**Issue by Lars-B** [bioDS/beter#2]
The Usage section suggests this:
>process_template("template.xml", "config.toml", "result.xml")

This does not work, i had to switch it to `process_template("template.xml", "result.xml", "config.toml")` instead.
Maybe using named arguments for the example is a good idea.

**Comment by J-Moravec** [comment]
That is a bug in `README.md`. There is more detailed info in vignettes, which are shown on the webpage, and info I think the documentation in  `?process_template` is detailed enough. `README.md` is supposed to give only a small taste, a faint idea, not provide detailed documentation (for this, vignettes are used). For this reason, the short form (without named arguments) is used. It is not even a minimal example.

But if you still think otherwise, I am happy to change it.

**Comment by Lars-B** [comment]
If there is code in the readme it should be executable, that is all i am suggesting 👍🏻

**Comment by J-Moravec** [comment]
In that case, this was fixed in https://github.com/bioDS/beter/commit/48dfd15b5d87d5c7b75281858d55f892c64ff16f
